name: Release and publish to npm

on: 
  workflow_dispatch:
    inputs:
      semantic_version:
        description: 'Semantic release version (major | minor | patch)'
        required: true
        default: 'patch'

jobs:
  release_and_deploy:
    name: Release and publish
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Bump version and commit
      run: |
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "Release action on behalf of ${{ github.actor }}"
        npm version ${{ github.event.inputs.semantic_version }} -m 'Release %s'

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        tags: true

    - name: Publish if version has been updated
      uses: mkiki/npm-publish-action@c4315ef5790b7bcec2cbb75b34e37681a409d78d
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
        NPM_AUTH: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
